global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cidadao-ai-monitor'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Cidadão.AI Backend Application Metrics
  - job_name: 'cidadao-ai-backend'
    static_configs:
      - targets: ['cidadao-ai:7860']
    metrics_path: /health/metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana Monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s

  # System Metrics via Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # Container Metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Alternative Health Check Endpoint
  - job_name: 'cidadao-ai-health'
    static_configs:
      - targets: ['cidadao-ai:7860']
    metrics_path: /health
    scrape_interval: 30s
    params:
      format: ['json']